language: python
python:
- '2.7'
- '3.4'
install: pip install -U setuptools; pip install .
script: nosetests
sudo: false
deploy:
  provider: pypi
  skip_cleanup: true
  user: sre
  password:
    secure: Ujsadj3GadyzgCqDarA4qdW6DTTQQBOtSG/5zpqu0eui8Ws12CZcVfPDwB+Q3gj+mjkef2Ea4tsTxmHgZADx2fKlAG2VlKWxbRP310Sk2qfjqwOnCRWc3p93KFEMEsapFiq8jwlW6q9C4L4YQ4gAO6rDoKCyn7WOmK3c582yAYA=
  on:
    tags: true
    all_branches: true
    repo: prismicio/python-kit
